---
scope:
  account: staging

account:
  number: "111111111111"
  default_region: us-west-2
  dns_zones: {}
  acm_certs: []

networks:
  staging:
    us-east-1:
      public:
        cidr: 10.10.0.0/16
        zones:
          a: 10.10.0.0/20
          b: 10.10.16.0/20
          c: 10.10.32.0/20
          d: 10.10.48.0/20
          e: 10.10.64.0/20
          f: 10.10.80.0/20
      private:
        cidr: 10.11.0.0/16
        zones:
          a: 10.11.0.0/20
          b: 10.11.16.0/20
          c: 10.11.32.0/20
          d: 10.11.48.0/20
          e: 10.11.64.0/20
          f: 10.11.80.0/20
    us-west-2:
      public:
        cidr: 10.34.0.0/16
        zones:
          a: 10.34.0.0/20
          b: 10.34.16.0/20
          c: 10.34.32.0/20
          d: 10.34.48.0/20
      private:
        cidr: 10.35.0.0/16
        zones:
          a: 10.35.0.0/20
          b: 10.35.16.0/20
          c: 10.35.32.0/20
          d: 10.35.48.0/20
    us-east-2:
      public:
        cidr: 10.58.0.0/16
        zones:
          a: 10.58.0.0/20
          b: 10.58.16.0/20
          c: 10.58.32.0/20
      private:
        cidr: 10.59.0.0/16
        zones:
          a: 10.59.0.0/20
          b: 10.59.16.0/20
          c: 10.59.32.0/20
